// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbqjC1cBAPCX76SzIteIM-ifD7_Ec8-fw',
    appId: '1:186453982356:web:66e721c8d73baabc398881',
    messagingSenderId: '186453982356',
    projectId: 'projetoflutterteste-6cd90',
    authDomain: 'projetoflutterteste-6cd90.firebaseapp.com',
    databaseURL: 'https://projetoflutterteste-6cd90-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutterteste-6cd90.appspot.com',
    measurementId: 'G-3XCCMXC6G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIg9Aknpk4wyk8qe7hkWzp_JMf0lv6j1Y',
    appId: '1:186453982356:android:4095dc7a318fd0e2398881',
    messagingSenderId: '186453982356',
    projectId: 'projetoflutterteste-6cd90',
    databaseURL: 'https://projetoflutterteste-6cd90-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutterteste-6cd90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_esfLM_KCEbkkOS0l8_T-6FcFUXeiY0',
    appId: '1:186453982356:ios:932e362b4d9871bc398881',
    messagingSenderId: '186453982356',
    projectId: 'projetoflutterteste-6cd90',
    databaseURL: 'https://projetoflutterteste-6cd90-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutterteste-6cd90.appspot.com',
    iosClientId: '186453982356-ibb8eej9d5iol420sp3tfnsm1396m2mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.projPi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg_esfLM_KCEbkkOS0l8_T-6FcFUXeiY0',
    appId: '1:186453982356:ios:932e362b4d9871bc398881',
    messagingSenderId: '186453982356',
    projectId: 'projetoflutterteste-6cd90',
    databaseURL: 'https://projetoflutterteste-6cd90-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutterteste-6cd90.appspot.com',
    iosClientId: '186453982356-ibb8eej9d5iol420sp3tfnsm1396m2mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.projPi',
  );
}
