// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoJQ4LcbZm-12FVEtl77TUbfNoroIBdno',
    appId: '1:909206631410:web:458752e73b1e0dcd53b16b',
    messagingSenderId: '909206631410',
    projectId: 'projetopi-7a832',
    authDomain: 'projetopi-7a832.firebaseapp.com',
    storageBucket: 'projetopi-7a832.appspot.com',
    measurementId: 'G-MKDVSJDRK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcA4YiMZRN9WlC8neTMHaGc-p0bTK-YA',
    appId: '1:909206631410:android:65b07d0a2c3e8ea653b16b',
    messagingSenderId: '909206631410',
    projectId: 'projetopi-7a832',
    storageBucket: 'projetopi-7a832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBujqYwWfj2Q9Osg_b6uRgqsAWlONBs3VU',
    appId: '1:909206631410:ios:0e543443d1c540e053b16b',
    messagingSenderId: '909206631410',
    projectId: 'projetopi-7a832',
    storageBucket: 'projetopi-7a832.appspot.com',
    iosClientId: '909206631410-5df69cv022gdk0hqo5hsgmugk8u7d1dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.projPi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBujqYwWfj2Q9Osg_b6uRgqsAWlONBs3VU',
    appId: '1:909206631410:ios:0e543443d1c540e053b16b',
    messagingSenderId: '909206631410',
    projectId: 'projetopi-7a832',
    storageBucket: 'projetopi-7a832.appspot.com',
    iosClientId: '909206631410-5df69cv022gdk0hqo5hsgmugk8u7d1dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.projPi',
  );
}
